artificialminds/MyProject/capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sample.urls', namespace='sample')),

]

artificialminds/MyProject/capstone/sample/urls.py
from django.urls import path
from . import views

app_name= 'sample'
urlpatterns = [
	path('', views.IndexView.as_view(), name="index"),
	path('register', views.RegistrationView.as_view(), name="register"),
	path('aregister', views.AdviserRegistrationView.as_view(), name="aregister"),
	path('login', views.login, name="login"),	
	path('alogin', views.alogin, name="alogin"),
	path('home', views.HomeView.as_view(), name="home"),
	path('ahome', views.AdviserHomeView.as_view(), name="ahome"),
	path('about', views.AboutView.as_view(), name="about"),
	path('aabout', views.AdviserAboutView.as_view(), name="aabout"),
	path('contact', views.ContactView.as_view(), name="contact"),
	path('acontact', views.AdviserContactView.as_view(), name="acontact"),
	path('setting', views.SettingView.as_view(), name="setting"),
	path('asetting', views.AdviserSettingView.as_view(), name="asetting"),
	path('logout', views.LogoutView.as_view(), name="logout"),
	path('setappointment', views.SetAppointmentView.as_view(), name="setappointment"),
	path('viewappointment', views.ViewAppointmentView.as_view(), name="viewappointment"),
	path('lobby/', views.lobby),
	path('videoroom/', views.videoroom),
	path('get_token/', views.getToken),
	path('create_member/', views.createMember),
	path('get_member/', views.getMember),
	path('delete_member/', views.deleteMember),
	path('chathome', views.chathome, name='chathome'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
    path('ratings', views.ratings, name="ratings"),

]

artificialminds/MyProject/capstone/sample/models.py
from django.db import models
from django import forms
from datetime import datetime


class Student(models.Model):
	studentID = models.AutoField(primary_key = True)
	firstname = models.CharField(max_length = 100)
	lastname = models.CharField(max_length = 100)
	idnum = models.CharField(max_length = 20)
	email = models.EmailField()
	course = models.CharField(max_length = 100)
	year = models.CharField(max_length = 100)
	gender = models.CharField(max_length = 100)
	contact = models.CharField(max_length = 100)
	password = models.CharField(max_length = 100)
	isLoggedIn = models.BooleanField(default = False)
	isDeleted = models.IntegerField(default = 0)


	class Meta:
		db_table = "student"


class Adviser(models.Model):
	adviserID = models.AutoField(primary_key = True)
	firstname = models.CharField(max_length = 100)
	lastname = models.CharField(max_length = 100)
	idnum = models.CharField(max_length = 20)
	email = models.EmailField()
	contact = models.CharField(max_length = 100)
	password = models.CharField(max_length = 100)
	available_anytime = models.IntegerField(default = 0)
	schedule_date = models.DateField(null=True)
	schedule_time = models.TimeField(null=True)
	isLoggedIn = models.BooleanField(default = False)
	isDeleted = models.IntegerField(default = 0)

	class Meta:
		db_table = "adviser" 

class Appointment(models.Model):
	appointmentID = models.AutoField(primary_key = True)
	student = models.ForeignKey(Student, null = False, blank = False, on_delete = models.CASCADE, related_name = "Student")
	meeting_counselor = models.ForeignKey(Adviser, null = False, blank = False, on_delete = models.CASCADE, related_name = "Adviser")
	meeting_type = models.CharField(max_length = 100)
	meeting_status = models.CharField(max_length = 100, default = "pending")
	meeting_date = models.DateField(default = datetime.now()) 
	meeting_time = models.TimeField(null = False)
	is_Approved = models.IntegerField(default = 0)

	class Meta:
		db_table = "appointment"


class RoomMember(models.Model):
	name = models.CharField(max_length=200)
	uid = models.CharField(max_length=200)
	room_name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Room(models.Model):
	name = models.CharField(max_length=1000)

class Message(models.Model):
	value = models.CharField(max_length=1000)
	date = models.DateTimeField(default=datetime.now, blank=True)
	user = models.CharField(max_length=1000)
	room = models.CharField(max_length=1000)

artificialminds/MyProject/capstone/sample/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class StudentForm(forms.ModelForm):

	class Meta:
		model = Student
		fields = ('firstname','lastname','idnum','email','course','year','gender','contact','password')

class AdviserForm(forms.ModelForm):

	class Meta:
		model = Adviser
		fields = ('firstname','lastname','idnum','email','contact','password')


class AppointmentForm(forms.ModelForm):

	class Meta:
		model = Appointment
		fields = ('meeting_type','meeting_date','meeting_time','meeting_counselor')

artificialminds/MyProject/capstone/sample/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import View
from .forms import *
from django.contrib import messages
from .models import *
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate, login
# Imports for Video Calling
from agora_token_builder import RtcTokenBuilder
from django.http import JsonResponse
import random
import time
import json

from .models import RoomMember
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

class IndexView(View):
		def get(self, request):
			return render(request, 'index.html')

		# def post(self, request):
		# 	if 'login' in request.POST:
		# 		return redirect('sample:register')


class RegistrationView(View):
		def get(self, request):
			return render(request, 'register.html')

		def post(self, request):
			form = StudentForm(request.POST)

			if form.is_valid():
				firstname = request.POST['firstname']
				lastname = request.POST['lastname']
				idnum = request.POST['idnum']
				email = request.POST['email']
				course = request.POST['course'] 
				year = request.POST['year']
				gender = request.POST['gender']
				contact = request.POST['contact']
				password = request.POST['password']
				cpassword = request.POST['cpassword']

				if password != cpassword:
					messages.error(request, 'Password do not match!')
					return redirect('sample:register')

				elif password == cpassword:
					form = Student(firstname=firstname, lastname=lastname, idnum = idnum, email = email,  course = course, year = year, gender = gender, contact = contact, password = password)
					form.save()
					print('student created')
					#messages.success(request, 'Your account has been successfully registered!')
					return redirect('sample:login')


class AdviserRegistrationView(View):
		def get(self, request):
			return render(request, 'registerAdviser.html')

		def post(self,request):
			form = AdviserForm(request.POST)

			if form.is_valid():
				firstname = request.POST['firstname']
				lastname = request.POST['lastname']
				idnum = request.POST['idnum']
				email = request.POST['email']
				contact = request.POST['contact']
				password = request.POST['password']
				cpassword = request.POST['cpassword']

				if password != cpassword:
					messages.error(request, 'Password do not match')
					return redirect('sample:aregister')

				elif password == cpassword:
					form = Adviser(firstname=firstname, lastname=lastname, idnum = idnum, email = email, contact = contact, password = password)	
					form.save()
					print('adviser created')
					return redirect('sample:alogin')

def login(request):
	if request.method == 'POST':
		email = request.POST.get('email')
		password = request.POST.get('password')
		students = Student.objects.all()

		if Student.objects.filter(email=email).count() != 0 :
			account = Student.objects.get(email=email)
			print('account')
			if account.password == password:
				print('login successful')
				Student.objects.filter(email=email).update(isLoggedIn = True)
				return redirect('/home?'+email)

			elif account.password != password: 
				messages.error(request, 'Incorrect Password')
				return render(request,'login.html')

		else:
			messages.error(request, 'Username does not exist!')
			return render(request,'login.html')
	else:
		return render(request,'login.html')

def alogin(request):
	if request.method == 'POST':
		email = request.POST.get('email')
		password = request.POST.get('password')
		adviser = Adviser.objects.all()

		if Adviser.objects.filter(email=email).count() != 0:
			account = Adviser.objects.get(email=email)
			print('adviser account')
			if account.password == password:
				print('adviser login successful')
				Adviser.objects.filter(email=email).update(isLoggedIn = True)
				return redirect('/ahome?'+email)

			elif account.password != password:
				messages.error(request,'Incorrect Password')
				return render(request,'alogin.html')

		else:
			messages.error(request,'Username does not exist!')
			return render(request,'alogin.html')
	else:
		return render(request,'alogin.html')

class HomeView(View):
	def get(self, request):
		students = Student.objects.all()
		
		for student in students:
			if(student.isLoggedIn == True):
				return render(request, 'home.html', {'students':student})
	
		return redirect('sample:login')

class AdviserHomeView(View):
	def get(self, request):
		try:
			adviser_online = Adviser.objects.get(isLoggedIn = True)
		except:
			return redirect('sample:alogin')

		student = Student.objects.all()
		appointment = Appointment.objects.filter(meeting_counselor=adviser_online.adviserID,is_Approved=0)
	
		approved_chat = Appointment.objects.filter(meeting_counselor=adviser_online.adviserID,is_Approved=1,meeting_type = 'chat')
		approved_live = Appointment.objects.filter(meeting_counselor=adviser_online.adviserID,is_Approved=1,meeting_type = 'live')
		context ={
			'advisers':adviser_online,
			'students':student,
			'appointments':appointment,
			'approved_chat':approved_chat,
			'approved_live':approved_live,
			
		}
		
		if(adviser_online.isLoggedIn == True):
			return render(request, 'homeAdviser.html', context)

	def post(self, request):
		if request.method == 'POST':
			if 'btnApprove' in request.POST:	
				print('approve button clicked')
				sid = request.POST.get("sid")
				aid = request.POST.get("aid")
				apid = request.POST.get("apid")
				print(sid)
				print(aid)
				print(apid)
				update_appointment_status = Appointment.objects.filter(student_id = sid, meeting_counselor_id = aid, appointmentID =apid).update(is_Approved = 1, meeting_status='approved')

				print('appointment approved')
				return redirect('sample:ahome')

			elif 'btnUpdate' in request.POST:
				print('Update Button Clicked')
				sid = request.POST.get("sid")
				aid = request.POST.get("aid")
				apid = request.POST.get("apid")
				meeting_date = request.POST.get("newdate")
				meeting_time = request.POST.get("newtime")
				print(meeting_date)
				print(meeting_time)

				update_appointment = Appointment.objects.filter(student_id = sid, meeting_counselor_id = aid, appointmentID = apid).update(meeting_date = meeting_date, meeting_time = meeting_time,is_Approved = 1, meeting_status='re-scheduled' )

				print('appointment updated')
				return redirect('sample:ahome')	
			
class AboutView(View):
		def get(self, request):
			students = Student.objects.all()

			for student in students:
				if(student.isLoggedIn == True):
					return render(request, 'about.html', {'students':student})

			return redirect('sample:login')		

class ContactView(View):
		def get(self, request):
			students = Student.objects.all()

			for student in students:
				if(student.isLoggedIn == True):
					return render(request, 'contact.html', {'students':student})

			return redirect('sample:login')		
			
class SettingView(View):
		def get(self, request):
			students = Student.objects.all()

			for student in students:
				if(student.isLoggedIn == True):
					return render(request, 'setting.html', {'students':student})

			return redirect('sample:login')		

		def post(self, request):
			if request.method == 'POST':
				if 'btnUpdate' in request.POST:
					print('update button clicked')
					sid = request.POST.get("sid")
					firstname = request.POST.get("firstname")
					lastname = request.POST.get("lastname")
					email = request.POST.get("email")
					contact = request.POST.get("contact")
					course = request.POST.get("course")
					year = request.POST.get("year")
					
					update_student = Student.objects.filter(studentID = sid).update(firstname = firstname, lastname = lastname, email = email, contact = contact, course = course, year = year)

					print(update_student)
					return redirect('sample:home')
					
class LogoutView(View):
	def get(self, request):
		students = Student.objects.all()
		advisers = Adviser.objects.all()

		for student in students:
			if(student.isLoggedIn == True):
				Student.objects.update(isLoggedIn = False)
				print('user successfully log out')
				return redirect('sample:index')

		for adviser in advisers:
			if(adviser.isLoggedIn == True):
				Adviser.objects.update(isLoggedIn = False)
				print('user successfully log out')
				return redirect('sample:index')
		

class SetAppointmentView(View):
		def get(self, request):
			advisers = Adviser.objects.all()
			students = Student.objects.all()

			for student in students:
				if(student.isLoggedIn == True):
					return render(request, 'setappointment.html', {'students':student, 'adviser':advisers})

		def post(self, request):
			form = AppointmentForm(request.POST)

			if form.is_valid():
				student_id = request.POST['student_id']
				meeting_type = request.POST['meeting_type']
				meeting_counselor_id = request.POST['meeting_counselor']
				meeting_date = request.POST['meeting_date']
				meeting_time = request.POST['meeting_time']

				form = Appointment(meeting_type=meeting_type, meeting_counselor_id=meeting_counselor_id, meeting_date=meeting_date, meeting_time=meeting_time, student_id=student_id)
				form.save()
				print('appointment saved')
				return redirect('sample:home')
			
			else:
				return redirect('sample:setappointment')

class ViewAppointmentView(View):
		def get(self, request):
			adviser = Adviser.objects.all()
			student_online = Student.objects.get(isLoggedIn = True)
			appointment = Appointment.objects.filter(student = student_online.studentID)
			chat_appointment = Appointment.objects.filter(student = student_online.studentID, meeting_type='chat')
			live_appointment = Appointment.objects.filter(student = student_online.studentID, meeting_type='live')

			context ={
				'advisers':adviser,
				'students':student_online,
				'appointments':appointment,
				'live_appointment':live_appointment,
				'chat_appointment':chat_appointment,
			}

			if(student_online.isLoggedIn == True):

artificialminds/MyProject/capstone/sample/templates/alogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In | CIT by ArtificialMinds</title>
    <link rel="shortcut icon" type="image/png" href="../static/img/images/favicon1.png">
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>

    <section>
        <div class="circle3">
        </div>
        <header>
            <a href="{% url 'sample:index' %}"><img src="../static/img/images/logov3.png" class="logo"></a>
        </header>
        <div class="content">
                <!-- <div class="imgBox">
                    <img src="../static/img/images/img4.png" class="logo" style="width: 500px; height:auto; margin-right: 650px; margin-top: -200px; ">
                </div>  -->
        </div>
        <div class="wrapper">
         
            <form action="alogin" method="POST">
                  {% csrf_token %}
                
                <h2>Log in to your account</h2>
              <div class="field id">
                <div class="sign-txt" style="font-size: 12px;">Not yet member? <a href="{% url 'sample:aregister' %}">Sign  up.</a> <br><br></div>
                <div class="input-area">
                  <input autocomplete="off" type="email" name="email" placeholder="ID number or Email">
                  <i class="icon fas fa-envelope"></i>
                  <i class="error error-icon fas fa-exclamation-circle"></i>
                </div>
                <div class="error error-txt">ID can't be blank</div>
              </div>
              <div class="field password">
                <div class="input-area">
                  <input type="password" name="password" placeholder="Password">
                  <i class="icon fas fa-lock"></i>
                  <i class="error error-icon fas fa-exclamation-circle"></i>
                </div>
                <div class="error error-txt">Password can't be blank</div>
              </div>
              <div class="pass-txt" style="font-size: 12px;"><a href="#">Forgot password?</a></div>

              <input class="btn" type="submit" value="Continue">

              {% for message in messages %}
              <h6 style="color:red"> {{message}} </h6>
              {% endfor %}
            </form>
            <div class="sign-txt" style="font-size: 14px;" ><p>By continuing, you agree to our <a href="#">Terms of Service.</a></p></div>
          </div>
      
          <script src="script.js"></script>
        <div class="circle4">
        </div>
    </section>
</body>
</html> 

artificialminds/MyProject/capstone/sample/templates/asetting.html
{% extends "base2.html" %}

{% load static %}

    {% block title %} Settings | ArtificialMinds {% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="../static/css/asettings.css">
    {% endblock%}

    {% block nav_setting %}active{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="title">
      Update Profile
    </div>
   
    <div class="form">
    <form id="updateForm" method="post">
         {% csrf_token %}

            <input type="text" class="input" name="sid" value="{{advisers.adviserID}}" placeholder="{{advisers.adviserID}}" hidden>

        <div class="inputfield">
            <label>First Name</label>
            <input type="text" class="input" name="firstname" value="{{advisers.firstname}}" placeholder="{{advisers.firstname}}">
        </div>  
        <div class="inputfield">
          <label>Last Name</label>
           <input type="text" class="input" name="lastname" value="{{advisers.lastname}}" placeholder="{{advisers.lastname}}">
        </div>
        
        <div class="inputfield">
            <label>Email Address</label>
            <input type="email" class="input" name="email" value="{{advisers.email}}" placeholder="{{advisers.email}}">
        </div> 
        <div class="inputfield">
            <label>Phone Number</label>
             <input type="text" class="input" name="contact" value="{{advisers.contact}}" placeholder="{{advisers.contact}}">
        </div><br>

        <div class="inputfield terms">
          <p>Please review before clicking update.</p>
        </div> 

        <div class="inputfield">
            <input type="submit" name="btnUpdate" class="btn">
        </div>
    </form>
    </div>
   
</div>	
{% endblock %}

artificialminds/MyProject/capstone/sample/templates/base2.html
<!DOCTYPE html>
    <html lang="en" dir="ltr">
      <head>
        {% load static %}
        <meta charset="utf-8">
        <title>{% block title %} ArtificialMinds {% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../static/css/base.css">
        {% block css %} {% endblock %}
        <link rel="shortcut icon" type="image/png" href="../static/img/images/favicon1.png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.css">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        
      </head>
      <body>

        <nav>
          <input type="checkbox" id="check">
          <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
          </label>
          <label class="logo"><img class="logo" src="../static/img/images/logoV2.png"></label>
             
            <ul>
              <li style="color: white; margin-right: 20px; font-size: 12px; pointer-events: none;">
              
                {% if advisers.isLoggedIn == True %}
                      Welcome Adviser, {{advisers.firstname}}
                {% endif %}
              </li>
              <li>
                  <a class="{% block nav_home %}{% endblock %}" href="{% url 'sample:ahome' %}"><i class="fa-solid fa-house-chimney"></i>Home</a>
              </li>
              <li>
                  <a class="{% block nav_about %}{% endblock %}" href="{% url 'sample:aabout' %}"><i class="fa-solid fa-address-card"></i>About</a>
              </li>
              <li>
                  <a class="{% block nav_setting %}{% endblock %}" href="{% url 'sample:asetting' %}"><i class="fa-solid fa-gears"></i>Setting</a>
              </li>
              <li>
                  <a class="{% block nav_logout %}{% endblock %}" href="{% url 'sample:logout' %}"><i class="fa-solid fa-user-astronaut"></i>Log Out</a>
              </li>
            </ul>
        </nav>

          {% block content %}{% endblock %}
          
      </body>
    </html>
    

artificialminds/MyProject/capstone/sample/templates/chathome.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="../static/css/chathome.css">
<link rel="shortcut icon" type="image/png" href="../static/img/images/favicon1.png">
<title>Chat Room | ArtificialMinds </title>
</head>
<body>
  <section id="form-container">
		<img id="logo" src="{% static 'img/images/chat-icon.png' %}" />

		<div id="welcome-message">
			<h1>Start Conversation</h1>
			<p>Emotion recognition application just for you</p>
		</div>

    <form id="post-form" method="POST" action="checkview">
      {% csrf_token %}
      <div class="form-field">
        <input type="text" name="room_name" id="room_name" width="100px" placeholder="Enter room name without spaces" autocomplete="off" />
      </div>
      <div class="form-field">
        <input type="text" name="username" id="username" width="100px"  placeholder="Enter username"  autocomplete="off" />
      </div>
      <div class="form-field">
        <p>By clicking "ENTER", you agree to our Terms of Service and Privacy Statement.</p>
      </div>
      <div class="form-field">
        <input type="submit" value="Enter">
      </div>
    
      
  </form>
	</section>
</body>

</html>

artificialminds/MyProject/capstone/sample/templates/chatroom.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="../static/css/chatroom.css">
<link rel="shortcut icon" type="image/png" href="../static/img/images/favicon1.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.css">
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<title>Chat Room | ArtificialMinds </title>
</head>
<body>

  <div class="circle"></div>
	<header class="header">
		<a href="#"><img src="../static/img/images/logoV3.png" class="logo"></a>	
	</header>
	<div class="circle46"></div>

  <div class="box">
    <h2>Chat Room: {{room}}</h2>
    <p>Note: Messages are secured with end-to-end encryption.</p>

    <div id="display" class="display">
    <!-- <div class="container darker">
      <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
      <span class="time-left">20th, April 2021</span>
    </div> -->
  
    </div>
  
    <div class="container">
        <form id="post-form">
            {% csrf_token %}
            <input type="hidden" name="username" id="username" value="{{username}}"/>
            <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}"/>
            <input type="text" name="message" id="message" width="100px" autocomplete="off" placeholder="Aa"/>
            <button type="submit"><i class="fa-solid fa-paper-plane"></i></button>
        </form>
    </div>
  
  </div>
  

</body>
<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/send',
      data:{
          username:$('#username').val(),
          room_id:$('#room_id').val(),
          message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>


<script>
  $(document).ready(function(){
  
  setInterval(function(){
      $.ajax({
          type: 'GET',
          url : "/getMessages/{{room}}/",
          success: function(response){
              console.log(response);
              $("#display").empty();
              for (var key in response.messages)
              {
                  var temp="<div class='container darker'><b class='name'>"+response.messages[key].user+"</b><p class='msg'>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                  $("#display").append(temp);
              }
          },
          error: function(response){
              alert('An error occured')
          }
      });
    },1000);
  })
</script>
<script>
  var objDiv = document.getElementById("display");
  objDiv.scrollTop = objDiv.scrollHeight;
</script>
</html>

artificialminds/MyProject/capstone/sample/templates/contact.html
{% extends "base.html" %}


{% load static %}

    {% block title %} Contact | ArtificialMinds {% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="../static/css/contact.css">
    {% endblock%}

    {% block nav_contact %}active{% endblock %}

{% block content %}
<h2>contact PAGE</h2>
{% endblock %}

artificialminds/MyProject/capstone/sample/templates/lobby.html
<!DOCTYPE html>
<html>
{% extends 'main.html' %}
{% load static %}

{% block content %}

<main>

	<section id="form-container">
		<img id="logo" src="{% static 'img/images/chat-icon.png' %}" />

		<div id="welcome-message">
			<h1>Join Meeting</h1>
			<p>Emotion recognition application just for you</p>
		</div>

		<form id="form">
			<div class="form-field">
				<input autocomplete="off" type="text" name="room" placeholder="Enter room name" />
			</div>

			<div class="form-field">
				<input autocomplete="off" type="text" name="username" placeholder="Enter Name" />
			</div>
			<div class="form-field">
				<p>By clicking "JOIN", you agree to our Terms of Service and Privacy Statement.</p>
			</div>
			<div class="form-field">
				<input type="submit" value="Join" />
			</div>

		</form>
	</section>

</main>

<script>
    let form = document.getElementById('form')

    let handleSubmit = async (e) => {
        e.preventDefault()
        let room = e.target.room.value.toUpperCase()
        let name = e.target.username.value

        let response = await fetch(`/get_token/?channel=${room}`)
        let data = await response.json()

        let UID = data.uid
        let token = data.token

        sessionStorage.setItem('UID', UID)
        sessionStorage.setItem('token', token)
        sessionStorage.setItem('room', room)
        sessionStorage.setItem('name', name)

        window.open('/videoroom/', '_self')
    }



    form.addEventListener('submit', handleSubmit)
</script>

{% endblock content %}

</html>

artificialminds/MyProject/capstone/sample/templates/logout.html
{% extends "base.html" %}

{% load static %}

    {% block title %} Logout | ArtificialMinds {% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="../static/css/logout.css">
    {% endblock%}

    {% block nav_logout %}active{% endblock %}

{% block content %}
    <h2>logout</h2>
{% endblock %}

artificialminds/MyProject/capstone/sample/templates/room.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load static %}

{% block content %}

<main>
	<div class="circle"></div>
	<header class="header">
		<a href="#"><img src="../static/img/images/logoV3.png" class="logo"></a>	
	</header>
	<div class="circle46"></div>
	<section id ="room-name-wrapper">
		<p>Room Name: <strong><span id="room-name"></span></strong></p>
	</section>

	<section id="video-streams"></section>

	<section id="controls-wrapper">
		<div class="icon-wrapper">
			<img class="control-icon" id="mic-btn" src="{% static 'img/images/microphone.svg' %}">
		</div>

		<div class="icon-wrapper">
			<img class="control-icon" id="camera-btn" src="{% static 'img/images/video.svg' %}">
		</div>

		<div class="icon-wrapper">
			<img class="control-icon" id="leave-btn" src="{% static 'img/images/leave.png' %}">
		</div>

	
		
	</section>

</main>
<script type="text/javascript" src="{% static 'assets/AgoraRTC_N-4.10.2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/streams.js' %}"></script>

{% endblock content %}